project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Posts 

format:
  html:
    theme: spacelab 
    css: styles.css
    toc: true



